version: '3'

services:
  app:
    image: node:14-alpine3.14
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    command: npx nodemon
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.10
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-example}
    volumes:
      - dbdata:/data/db
    ports:
      - ${MONGODB_PORT:-27017}:27017

  mosquitto:
    image: eclipse-mosquitto:2.0.13
    volumes:
      - mosquittodata:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - ${MQTT_PORT:-1883}:1883
volumes:
  dbdata:
  mosquittodata:
